plugins {
    id 'com.android.library'
}

android {
    compileSdk rootProject.tools.compileSdk

    namespace 'com.github.barteksc.pdfviewer'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "${rootProject.tools.versionName}"
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

group = 'education.honor'
version = "${rootProject.tools.versionName}"

dependencies {
    implementation 'androidx.core:core:1.13.1'
}


ext {
    PUBLISH_GROUP_ID = 'education.honor'
    PUBLISH_VERSION = "${rootProject.tools.versionName}"
    PUBLISH_ARTIFACT_ID = 'honor-android-pdf-viewer'
}

apply from: "${rootProject.projectDir}/android-pdf-viewer/publish-mavencentral.gradle"